name: pynstein-env

channels:
  - conda-forge
  - defaults

dependencies:
  - astropy
  - coverage
  - matplotlib
  - notebook
  - numpy
  - pip
  - pip:
      - palettable
  - pytest
  - pytest-mock
  - scipy
  - sympy
